FROM yobasystems/alpine

#add testing repository
#COPY repositories /etc/apk/repositories
#RUN echo "@testing https://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN echo "https://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

RUN apk -U add --no-cache mariadb mariadb-client pwgen bash nano unixodbc unixodbc-dev mariadb-connector-odbc && \
    rm -f /var/cache/apk/*

ADD run-db.sh /scripts/run.sh
#adds config to listen on all available interfaces
ADD mariadb-server.cnf /etc/my.cnf.d/mariadb-server.cnf
RUN mkdir /scripts/pre-exec.d && \
    mkdir /scripts/pre-init.d && \
    chmod -R 755 /scripts
COPY setup.sql /docker-entrypoint-initdb.d/setup.sql

EXPOSE 3306

VOLUME ["/var/lib/mysql"]

#RUN mysql_install_db --user=mysql --ldata=/var/lib/mysql/

ENTRYPOINT ["/scripts/run.sh"]
