# either port forward/allow 16000 port so you can connect to it over IP directly
# or use reverse proxy such as nginx or caddy to map localhost:16000 or liquidms:16000 to your URI
version: "3.8"
services:
  caddy: #caddy reverse-proxy for the FastCGI-sattelite
    hostname: liquidms
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile_caddy # hook Caddy into sattelite
    environment:
      TZ: $TZ
    ports:
      - "${LIQUIDMS_PORT_HTTPS}:443" # Provide SSL port
      - "${LIQUIDMS_PORT}:80" #exposes LiquidMS's 80 port to .env port on the host machine
    depends_on:
      - satellite # connect up
    networks:
      - liquidms-net
      - external
  satellite: #has php-fpm with extensions and composer, check Dockerfile!
    hostname: liquidms
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile_satellite #also installs ODBC driver
      args:
        ODBC_HOST: $ODBC_HOST
        ODBC_PORT: $ODBC_PORT
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    environment:
      TZ: $TZ
      PHP_MEMORY_LIMIT: 1024M
    ports:
      - "5029:5029" # make SRB2Query work
    depends_on:
      - db #installs and runs database first before starting liquidms
    networks:
      - liquidms-net
      - external
  snitch: #has php-fpm with extensions and composer, check Dockerfile!
    hostname: liquidms
    build: 
      context: .
      dockerfile: Dockerfile_snitch #also installs ODBC driver
      args:
        ODBC_HOST: $ODBC_HOST
        ODBC_PORT: $ODBC_PORT
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    environment:
      TZ: $TZ
      PHP_MEMORY_LIMIT: 1024M
    networks:
      - liquidms-net
      - external # Access external nodes
  db:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile_mariadb #also installs ODBC driver
      args:
        ODBC_HOST: $ODBC_HOST
        ODBC_PORT: $ODBC_PORT
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    environment:
      TZ: $TZ
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "${ODBC_PORT}:3306" # Make MariaDB accessible across the Docker network
    networks:
      - liquidms-net

networks:
  liquidms-net:
    internal: true
  external:
