# either port forward/allow 16000 port so you can connect to it over IP directly
# or use reverse proxy such as nginx or caddy to map localhost:16000 or liquidms:16000 to your URI
name: liquidms
services:
  caddy: #caddy reverse-proxy for the FastCGI-sattelite
    image: caddy:2.6.2-alpine
    restart: unless-stopped
    environment:
      TZ: $TZ
    ports:
      - "443:443" # Provide SSL port
      - "${LIQUIDMS_PORT}:80" #exposes LiquidMS's 80 port to .env port on the host machine
    depends_on:
      #- satellite # connect up
      - frontend # Frontend server
      - api-srb2http # HTTP API server
    networks:
      - liquidms-net
      - external
    volumes:
      - type: bind
        source: docker/caddy/Caddyfile
        target: /etc/caddy/Caddyfile
      - type: bind
        source: dist/
        target: /var/www/liquidms/
  api-srb2http: #has php-fpm with extensions and composer, check Dockerfile!
    restart: unless-stopped
    build: 
      dockerfile: docker/apis/srb2http/Dockerfile #also installs ODBC driver
      args:
        ODBC_HOST: $ODBC_HOST
        ODBC_PORT: $ODBC_PORT
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    environment:
      TZ: $TZ
      PHP_MEMORY_LIMIT: 1024M
    depends_on:
      - liquidms-db # installs and runs database first before starting liquidms
    volumes:
      - type: bind
        source: dist/
        read_only: true
        target: /var/www/liquidms/
    ports:
      - "9000:9000" # PHP FastCGI port
    networks:
      - liquidms-net
      - external
  frontend: #has php-fpm with extensions and composer, check Dockerfile!
    restart: unless-stopped
    build: 
      dockerfile: docker/browser/Dockerfile #also installs ODBC driver
      args:
        ODBC_HOST: $ODBC_HOST
        ODBC_PORT: $ODBC_PORT
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    environment:
      TZ: $TZ
      PHP_MEMORY_LIMIT: 1024M
    volumes:
      - type: bind
        read_only: true
        source: dist/
        target: /var/www/liquidms/
    networks:
      - liquidms-net
      - external
  snitch: #has php-fpm with extensions and composer, check Dockerfile!
    build: 
      dockerfile: docker/snitch/Dockerfile #also installs ODBC driver
      args:
        ODBC_HOST: $ODBC_HOST
        ODBC_PORT: $ODBC_PORT
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    environment:
      TZ: $TZ
      PHP_MEMORY_LIMIT: 1024M
    volumes:
      - type: bind
        read_only: true
        source: docker/snitch/config.yaml
        target: /var/www/liquidms/config.yaml
    networks:
      - liquidms-net
      - external # Access external nodes
  liquidms-db:
    restart: always
    image: mariadb:latest
    #build:
      #dockerfile: docker/db/Dockerfile
      #args:
        #ODBC_HOST: $ODBC_HOST
        #ODBC_PORT: $ODBC_PORT
        #MYSQL_DATABASE: $MYSQL_DATABASE
        #MYSQL_USER: $MYSQL_USER
        #MYSQL_PASSWORD: $MYSQL_PASSWORD
        #MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    environment:
      TZ: $TZ
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - type: bind
        source: docker/db/initdb.d
        target: /docker-entrypoint-initdb.d
    networks:
      - liquidms-net
networks:
  liquidms-net:
    internal: true
  external:
