# either port forward/allow 16000 port so you can connect to it over IP directly
# or use reverse proxy such as nginx or caddy to map localhost:16000 or liquidms:16000 to your URI
name: liquidms
services:
  http: #has php-fpm with extensions and composer, check Dockerfile!
    restart: unless-stopped
    build: 
      dockerfile: docker/php.Dockerfile #installs necessary modules etc.
    environment:
      TZ: $TZ
      PHP_MEMORY_LIMIT: 1024M
    depends_on:
      - db 
    volumes:
      ### HTTP APIs are mounted one-by-one for
      ### flexibility and added isolation.
      ###
      ### well-known: Webfinger API for ChaosNet
      - type: bind
        source: src/apis/webfinger
        read_only: true
        target: /var/www/html/.well-known/webfinger
      ### HTTP-based game APIs
      - type: bind
        source: src/apis/chaosnet
        read_only: true
        target: /var/www/html/api/chaosnet
      - type: bind
        source: src/apis/srb2http
        read_only: true
        target: /var/www/html/api/srb2http
      - type: bind
        source: src/apis/srb2kart
        read_only: true
        target: /var/www/html/api/srb2kart
      ### (Legacy) Snitch API
      - type: bind
        source: src/apis/snitch
        read_only: true
        target: /var/www/html/api/snitch
      ### Web frontend
      - type: bind
        source: src/frontend
        read_only: true
        target: /var/www/html/web
    ports:
      - "443:443" # SSL/HTTPS
      - "80:80" # HTTP
    networks:
      - liquidms-net
      - default  
  api-srb2query: 
    restart: unless-stopped
    build: 
      dockerfile: docker/php.Dockerfile #installs necessary modules etc.
    environment:
      TZ: $TZ
      PHP_MEMORY_LIMIT: 1024M
    volumes:
      - type: bind
        source: src/apis/srb2query
        target: /var/www/liquidms/
    ports:
      - "5029:5029" # PHP FastCGI port
    networks:
      - liquidms-net
      - default
  api-srb2legacy: 
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    build: 
      dockerfile: src/apis/srb2legacy/Dockerfile
    develop:
      watch:
        - action: rebuild
          path: src/apis/srb2legacy/
          target: /usr/src/app/
    depends_on:
      - db
    #volumes:
    #  - type: bind
    #    source: src/apis/srb2legacy
    #    target: /usr/src/app/
    ports:
      - "28900:28900" # Standard SRB2Legacy port
    networks:
      - liquidms-net
      - default
  api-darkplaces: 
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    build: 
      dockerfile: src/apis/darkplaces/Dockerfile
    develop:
      watch:
        - action: rebuild
          path: src/apis/darkplaces/
          target: /usr/src/app/
    depends_on:
      - db
    ports:
      - "27950:27950/udp" # Standard Quake3Arena port
    networks:
      - liquidms-net
      - default
  snitch: #has php-fpm with extensions and composer, check Dockerfile!
    build: 
      dockerfile: docker/snitch/Dockerfile #installs necessary modules etc.
    develop:
      watch:
        - action: rebuild
          path: src/liquidanacron/
          target: /var/www/liquidms
    environment:
      TZ: $TZ
      PHP_MEMORY_LIMIT: 1024M
    network_mode: host
  db:
    restart: always
    image: mariadb:latest
    environment:
      TZ: $TZ
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - type: bind
        source: docker/db/initdb.d
        target: /docker-entrypoint-initdb.d
    networks:
      - liquidms-net
networks:
  liquidms-net:
    internal: true
