# syntax=docker/dockerfile:1
# Using multi-stage builds! https://docs.docker.com/develop/develop-images/multistage-build/

FROM caddy:2.6.2-alpine

COPY caddy.conf /etc/caddy/Caddyfile

#RUN echo "https://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
#RUN apk -U add --no-cache oniguruma oniguruma-dev unixodbc unixodbc-dev autoconf gcc libc-dev yaml yaml-dev make mariadb-connector-odbc php-fpm

#install liquidMS as an app (dist/)
COPY dist/ /var/www/liquidms
COPY satellite.config.yaml /var/www/liquidms/config.yaml
ADD install_config.sh /scripts/install_config.sh
RUN chmod +x /scripts/install_config.sh
RUN /scripts/install_config.sh

WORKDIR /var/www/liquidms

EXPOSE 80
EXPOSE 443

